// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workout-sets.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createWorkoutSets = `-- name: CreateWorkoutSets :many
WITH input_rows AS (
  SELECT 
    $1::int as workout_id,
    $2::int as exercise_id,
    unnest($3::int[]) set_number,
    unnest($4::int[]) reps,
    NULLIF(unnest($5::text[]), '')::decimal resistance_value,
    NULLIF(unnest($6::text[]), '')::resistance_type_enum resistance_type,
    unnest($7::text[]) resistance_detail,
    NULLIF(unnest($8::text[]), '')::decimal rpe,
    unnest($9::text[]) notes
)
INSERT INTO workout_sets 
(workout_id, exercise_id, set_number, reps, resistance_value, resistance_type, resistance_detail, rpe, notes)
SELECT workout_id, exercise_id, set_number, reps, resistance_value, resistance_type, resistance_detail, rpe, notes FROM input_rows
RETURNING workout_id, exercise_id, set_number, reps, resistance_value, resistance_type, resistance_detail, rpe, percent_1rm, notes, created_at
`

type CreateWorkoutSetsParams struct {
	Column1 int32
	Column2 int32
	Column3 []int32
	Column4 []int32
	Column5 []string
	Column6 []string
	Column7 []string
	Column8 []string
	Column9 []string
}

// RE: the "NULLIF" lines:
// they accept text arrays, convert empty strings to NULL, then cast non-NULL values to decimal
func (q *Queries) CreateWorkoutSets(ctx context.Context, arg CreateWorkoutSetsParams) ([]WorkoutSet, error) {
	rows, err := q.db.QueryContext(ctx, createWorkoutSets,
		arg.Column1,
		arg.Column2,
		pq.Array(arg.Column3),
		pq.Array(arg.Column4),
		pq.Array(arg.Column5),
		pq.Array(arg.Column6),
		pq.Array(arg.Column7),
		pq.Array(arg.Column8),
		pq.Array(arg.Column9),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutSet
	for rows.Next() {
		var i WorkoutSet
		if err := rows.Scan(
			&i.WorkoutID,
			&i.ExerciseID,
			&i.SetNumber,
			&i.Reps,
			&i.ResistanceValue,
			&i.ResistanceType,
			&i.ResistanceDetail,
			&i.Rpe,
			&i.Percent1rm,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAllWorkoutSets = `-- name: DeleteAllWorkoutSets :exec
DELETE FROM workout_sets
`

func (q *Queries) DeleteAllWorkoutSets(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllWorkoutSets)
	return err
}

const deleteWorkoutSetByID = `-- name: DeleteWorkoutSetByID :exec
DELETE FROM workout_sets 
WHERE workout_id = $1 
AND exercise_id = $2 
AND set_number = $3
`

type DeleteWorkoutSetByIDParams struct {
	WorkoutID  int32
	ExerciseID int32
	SetNumber  int32
}

func (q *Queries) DeleteWorkoutSetByID(ctx context.Context, arg DeleteWorkoutSetByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkoutSetByID, arg.WorkoutID, arg.ExerciseID, arg.SetNumber)
	return err
}

const deleteWorkoutSetsByExercise = `-- name: DeleteWorkoutSetsByExercise :exec
DELETE FROM workout_sets 
WHERE workout_id = $1 
AND exercise_id = $2
`

type DeleteWorkoutSetsByExerciseParams struct {
	WorkoutID  int32
	ExerciseID int32
}

func (q *Queries) DeleteWorkoutSetsByExercise(ctx context.Context, arg DeleteWorkoutSetsByExerciseParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkoutSetsByExercise, arg.WorkoutID, arg.ExerciseID)
	return err
}

const getAllWorkoutSets = `-- name: GetAllWorkoutSets :many
SELECT 
  ws.workout_id, ws.exercise_id, ws.set_number, ws.reps, ws.resistance_value, ws.resistance_type, ws.resistance_detail, ws.rpe, ws.percent_1rm, ws.notes, ws.created_at,
  e.exercise_name
FROM workout_sets ws
JOIN exercises e ON ws.exercise_id = e.exercise_id
WHERE ws.workout_id = $1
ORDER BY ws.exercise_id, ws.set_number
`

type GetAllWorkoutSetsRow struct {
	WorkoutID        int32
	ExerciseID       int32
	SetNumber        int32
	Reps             sql.NullInt32
	ResistanceValue  sql.NullString
	ResistanceType   NullResistanceTypeEnum
	ResistanceDetail sql.NullString
	Rpe              sql.NullString
	Percent1rm       sql.NullString
	Notes            sql.NullString
	CreatedAt        sql.NullTime
	ExerciseName     string
}

func (q *Queries) GetAllWorkoutSets(ctx context.Context, workoutID int32) ([]GetAllWorkoutSetsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllWorkoutSets, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllWorkoutSetsRow
	for rows.Next() {
		var i GetAllWorkoutSetsRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.ExerciseID,
			&i.SetNumber,
			&i.Reps,
			&i.ResistanceValue,
			&i.ResistanceType,
			&i.ResistanceDetail,
			&i.Rpe,
			&i.Percent1rm,
			&i.Notes,
			&i.CreatedAt,
			&i.ExerciseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkoutSetByID = `-- name: UpdateWorkoutSetByID :one
UPDATE workout_sets 
SET 
  reps = $3,
  resistance_value = $4,
  resistance_type = $5,
  resistance_detail = $6,
  rpe = $7,
  notes = $8
WHERE workout_id = $9 
AND exercise_id = $1 
AND set_number = $2
RETURNING workout_id, exercise_id, set_number, reps, resistance_value, resistance_type, resistance_detail, rpe, percent_1rm, notes, created_at
`

type UpdateWorkoutSetByIDParams struct {
	ExerciseID       int32
	SetNumber        int32
	Reps             sql.NullInt32
	ResistanceValue  sql.NullString
	ResistanceType   NullResistanceTypeEnum
	ResistanceDetail sql.NullString
	Rpe              sql.NullString
	Notes            sql.NullString
	WorkoutID        int32
}

// Make batch version of this later
func (q *Queries) UpdateWorkoutSetByID(ctx context.Context, arg UpdateWorkoutSetByIDParams) (WorkoutSet, error) {
	row := q.db.QueryRowContext(ctx, updateWorkoutSetByID,
		arg.ExerciseID,
		arg.SetNumber,
		arg.Reps,
		arg.ResistanceValue,
		arg.ResistanceType,
		arg.ResistanceDetail,
		arg.Rpe,
		arg.Notes,
		arg.WorkoutID,
	)
	var i WorkoutSet
	err := row.Scan(
		&i.WorkoutID,
		&i.ExerciseID,
		&i.SetNumber,
		&i.Reps,
		&i.ResistanceValue,
		&i.ResistanceType,
		&i.ResistanceDetail,
		&i.Rpe,
		&i.Percent1rm,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
